{% set name = "aiida-bigdft" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6522e57b7461e319840b15fef034c270ae7885614c23ced06573de3b3a1bb414

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - reentry
  run:
    - aiida-core >=1.1.1,<2.0.0
    - python >=3.7
    - six
    - voluptuous

test:
  imports:
    - aiida_bigdft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BigDFT-group/aiida-bigdft-plugin
  summary: Aiida plugin for BigDFT code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
